_wandb:
    value:
        cli_version: 0.18.5
        m: []
        python_version: 3.12.4
        t:
            "1":
                - 1
                - 5
                - 53
                - 55
            "2":
                - 1
                - 5
                - 53
                - 55
            "3":
                - 2
                - 13
                - 16
                - 23
                - 55
            "4": 3.12.4
            "5": 0.18.5
            "8":
                - 1
                - 5
            "12": 0.18.5
            "13": darwin-arm64
batch_size:
    value: 32
epochs:
    value: 100
learning_rate:
    value: 0.002
subset_train:
    value: 792
subset_val:
    value: 99
